name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 777 ~/.ssh/id_rsa
      env:
        WP_SSHG_KEY_PRIVATE: ${{ secrets.WP_SSHG_KEY_PRIVATE }}
        REMOTE_PATH: "wp-content/"
        - name: GitHub Action Deploy to WP
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@18.232.70.171 'cd /var/www/html/wordpress/wp-content && git pull'
        PHP_LINT: "true"
        CACHE_CLEAR: "true"
