name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP
      with:
        WP_SSHG_KEY_PRIVATE: ${{ secrets.WP_SSHG_KEY_PRIVATE }}
        REMOTE_PATH: "wp-content/"
        PHP_LINT: "true"
        CACHE_CLEAR: "true"
